version: '3.7'


# Use this compose file as reference or to build the image,
# but better to start the app from the main django-coleman compose
services:
  django-coleman-mtasks-viewer:
    image: "mrsarm/django-coleman-mtasks-viewer:${TAG:-latest}"
    build:
      context: .
      args:
        - BUILD
    ports:
      - "8888:8888"
    environment:
      - PORT
      - DCOLEMAN_ENDPOINT
      - DCOLEMAN_TASKS_VIEWER_HASH_SALT
      - DCOLEMAN_MASTER_TOKEN
    extra_hosts:
      - "django-coleman:${DJANGO_COLEMAN_IP}"
